name: TMate

on:
  workflow_dispatch:

jobs:
  tmate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run TMate
        run: bash ./actions-tmate.sh

      - name: Keep Alive
        if: ${{ success() }}
        run: bash ./actions-alive.sh